[tool.black]
line-length = 120
target-version = ['py312']
exclude = '''
/(
  | migrations
)/
'''

[tool.isort]
profile = "black"
line_length = 120
known_first_party = ["pybarker"]
extend_skip_glob = ["**/migrations"]
