# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-12 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelshistory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historymodelentry',
            name='item_object_id',
        ),
        migrations.RemoveField(
            model_name='historymodelentry',
            name='item_object_repr',
        ),
    ]
