# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelshistory', '0003_historymodelentry_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historymodelentry',
            name='object_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='object id'),
        ),
        migrations.AlterField(
            model_name='historymodelentry',
            name='tag',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
