# Generated by Django 3.2.8 on 2022-02-05 08:58

from django.db import migrations
import pybarker.django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('modelshistory', '0005_auto_20190125_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historymodelentry',
            name='comment',
            field=pybarker.django.db.models.fields.TruncatingCharField(blank=True, max_length=256, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='historymodelentry',
            name='newvalue',
            field=pybarker.django.db.models.fields.TruncatingCharField(blank=True, max_length=1024, null=True, verbose_name='new field value'),
        ),
        migrations.AlterField(
            model_name='historymodelentry',
            name='object_repr',
            field=pybarker.django.db.models.fields.TruncatingCharField(max_length=200, verbose_name='object repr'),
        ),
        migrations.AlterField(
            model_name='historymodelentry',
            name='oldvalue',
            field=pybarker.django.db.models.fields.TruncatingCharField(blank=True, max_length=1024, null=True, verbose_name='old field value'),
        ),
    ]
