# Generated by Django 3.2.12 on 2023-01-31 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelshistory', '0006_auto_20220205_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historymodelentry',
            old_name='tag',
            new_name='root_object_id',
        ),
    ]
