# Generated by Django 3.2.12 on 2023-02-26 16:56

from django.db import migrations, models
import django.db.models.deletion


# проверка что в данных нет null content_type (дальше мы делаем not-null)
def check_content_type_null(apps, schema_editor):
    print("check content_type null...")

    HistoryModelEntry = apps.get_model("modelshistory", "HistoryModelEntry")

    mhlogentries = HistoryModelEntry.objects.all()
    mhlogentries_count = mhlogentries.count()

    print("modelshistory all entries count:", mhlogentries_count)

    # null

    count = HistoryModelEntry.objects.filter(content_type__isnull=True).count()
    if count:
        raise Exception(f"object_id null count: {count}")


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('modelshistory', '0008_auto_20230210_1654'),
    ]

    operations = [
        migrations.RunPython(check_content_type_null),
        migrations.AlterField(
            model_name='historymodelentry',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype', verbose_name='content type'),
        ),
    ]
