# Generated by Django 3.2.19 on 2023-07-23 18:33

from django.db import migrations, models
import django.db.models.deletion

from django.contrib.contenttypes.models import ContentType


def populate_root_content_type(apps, schema_editor):
    HistoryModelEntry = apps.get_model("modelshistory", "HistoryModelEntry")
    all_content_type_id = HistoryModelEntry.objects.values_list("content_type", flat=True).order_by("content_type").distinct("content_type")
    for content_type_id in all_content_type_id:
        ct = ContentType.objects.get(id=content_type_id)
        print(f"\n=> content_type #{content_type_id} ({ct})")
        model_class = ct.model_class()
        print(f"   model: {model_class.__qualname__}")
        root_model = model_class.historylog.root_model
        print(f"   historylog.root_model: {root_model.__qualname__}")
        root_content_type = ContentType.objects.get_for_model(root_model)
        print(f"   root_content_type: {root_content_type}")
        # update
        mh_ct_items = HistoryModelEntry.objects.filter(root_content_type__isnull=True).filter(content_type_id=ct.id)
        print(f"   root_content_type is null && content_type='{ct}': {len(mh_ct_items)}")
        ret = mh_ct_items.update(root_content_type_id=root_content_type.id)
        print(f"      update: {ret}")


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('modelshistory', '0009_alter_historymodelentry_content_type'),
    ]

    operations = [

        # manual fixing
        migrations.AddField(
            model_name='historymodelentry',
            name='root_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.RunPython(populate_root_content_type),
        migrations.AlterField(
            model_name='historymodelentry',
            name='root_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype'),
        ),

        migrations.AlterField(
            model_name='historymodelentry',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype', verbose_name='content type'),
        ),
    ]
