# Generated by Django 3.2.25 on 2025-02-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelshistory', '0011_alter_historymodelentry_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historymodelentry',
            name='object_id',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='historymodelentry',
            name='root_object_id',
            field=models.CharField(max_length=36),
        ),
    ]
