# Generated by Django 3.2.25 on 2025-02-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelshistory', '0012_auto_20250218_1035'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='historymodelentry',
            index=models.Index(fields=['content_type_id', 'object_id', 'field'], name='modelshisto_content_8d968f_idx'),
        ),
    ]
